// Generated by CoffeeScript 1.7.1
(function() {
  var greet, parseArgs;

  greet = require('../lib/index');

  parseArgs = require('minimist');

  module.exports = function() {
    var argv;
    argv = parseArgs(process.argv.slice(2));
    return console.log(greet(argv._, argv.drunk));
  };

}).call(this);
